### ISSUE TITLE
Wilt and Sunflower have "extra" output

### ISSUE THREAD

**Issue by Petervos2018** [LeNomDesFleurs/NOI-VCVRACK#3]
Hi Noi, as you can see here they have an extra output that should not be there : 

![afbeelding](https://user-images.githubusercontent.com/46076474/213693829-05f34fc4-4344-4b6d-9605-3801c11b4e1e.png)

Rack 2.2.2 Free Windows 10.

Greetings Peter.

**Comment by LeNomDesFleurs** [comment]
Hey ! Thanks a lot, this have been patched, It shoud be updated in the next few days -ThomasFrom: Peter VosSent: Friday, 20 January 2023 13:22To: LeNomDesFleurs/NOI-VCVRACKCc: SubscribedSubject: [LeNomDesFleurs/NOI-VCVRACK] Wilt and Sunflouwer have "extra" output (Issue #3) Hi Noi, as you can see here they have an extra output that should not be there :Rack 2.2.2 Free Windows 10.Greetings Peter.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
